config/routes.rb
Rails.application.routes.draw do
  resources :properties
  devise_for :users
  
  root "properties#index"

  get "about" => "pages#about"
  get "user_properties" => "pages#user_properties"
  get "contact" => "pages#contact"

end

app/models/property.rb
class Property < ActiveRecord::Base
	belongs_to :user
    has_attached_file :image, styles: { medium: "600x600#", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :properties
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def user_properties
		@user_properties = current_user.properties
	end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  # GET /properties
  # GET /properties.json
  def index

    @properties = Property.all

    if user_signed_in? 
      @user_properties = current_user.properties
    end

  end

  # GET /properties/1
  # GET /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = current_user.properties.build
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = current_user.properties.build(property_params)
      if @property.save
        redirect_to @property, notice: 'Property was successfully created.' 
      else
        render :new 
      end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
      if @property.update(property_params)
        redirect_to @property, notice: 'Property was successfully updated.' 
      else
        render :edit 
      end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:direccion, :precio, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index

    @users = User.all

  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end


  def create
    @user = User.create(user_params)
      if @user.save
        redirect_to @user, notice: 'User was successfully created.' 
      else
        render :new 
      end
  end

  def update
      if @user.update(user_params)
        redirect_to @user, notice: 'User was successfully updated.' 
      else
        render :edit 
      end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_property
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :nombre, :apellido, :telefono, :encrypted_password, :sign_in_count, :current_sign_in_ip, :password_confirmation, )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_nav.html.erb
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand page-scroll" href="#page-top">Rita Balboa Propiedades</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <%= link_to "Inicio", root_path %>
                </li>
                <li>
                    <%= link_to "Acerca de Rita", about_path %>
                </li>
                <li>
                    <%= link_to "Contacto", contact_path %>
                </li>
                <% if !user_signed_in? %>
                <li><%= link_to "Iniciar Sesion", new_user_session_path %></li>
                <li><%= link_to "Registrarse", new_user_registration_path %></li>
                <% end %>

                <% if user_signed_in? %>
                <li><%= link_to "New Property", new_property_path %></li>
                <li><%= link_to "My Properties", user_properties_path %></li>
                <li><%= link_to "Log Out", destroy_user_session_path, :method => :delete %></li>
                <% end %>
            </ul>


        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RbProp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Creative - Start Bootstrap Theme</title>

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="/assets/bootstrap.min.css" type="text/css">

    <!-- Custom Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link rel="stylesheet" href="/assets/animate.min.css" type="text/css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="/assets/creative.css" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top">

	<%= render "layouts/nav" %>

	<% if !flash.empty? %>
		<div id="flash_messages">
		  <% flash.each do |key, value| %>
		    <%= content_tag(:div, value, :class => "flash #{key}") %>
		  <% end %>
		</div>
	<% end %>

	<%= yield %>

    <!-- jQuery -->
    <script src="/assets/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="/assets/bootstrap.min.js"></script>

    
    <script src="/assets/jquery.easing.min.js"></script>
    <script src="/assets/jquery.fittext.js"></script>
    <script src="/assets/wow.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="/assets/creative.js"></script>

</body>
</html>

app/views/pages/about.html.erb
<section class="city-bg" id="about">
    <div class="container-about">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
            	<%= image_tag "rita.png", class: "foto-rita" %>
                <h2 class="section-heading-about">Acerca de Rita</h2>
                <hr class="light">
                <p class="text-faded">Durante mi experiencia como corredora de propiedades me he dado cuenta de que no solo se realiza una transaccion comercial sino tambien un importante intercambio humano. Mi prioridad es casjhvbsdkjva vahjkbfvajdbvkuahdj vkae vjahevbaehj vkyuaerv ajehrvjhe vkaer vhea vaehjrv aehr vehv djhvkahdjv kaehr vhae djhe vhjda vjh jhsdbvjhasdv na dvjkhsbdvjhbsdjhvbas dvjhavjhds vjhasd vhjsv jhbsd vjhxbsjvhsd cjhavkyearv ajherv jweyvkawev kwuyvwayuv aywe vyukwav werh fke fgaer fmhea mhbed ahd fkage dfkgkdjhf kjhdf jhd h kjadhf ahjwe fjhd fjjfhwd fajhfjhaewf ajwe fjahewfjwahe ake gmaehjg amdb daj akjehr gaje fakedfhg ajkejghra kewhgvakgehae gkh gku3y kwuy4 kwhej ghawje gahjerg adb akgjdb jab khv adkjhva kjhfev kjrhv akejvg aekhvga krjhrva</p>
                <%= link_to "Comienza Ahora!", new_user_registration_path, class: "btn btn-default btn-xl" %>
            </div>
        </div>
    </div>
</section>

app/views/pages/contact.html.erb
<section class="city-bg" id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <h2 class="section-heading">Contacto</h2>
                <hr class="light">
                <p class="text-faded">Durante mi experiencia como corredora de propiedades me he dado cuenta de que no solo se realiza una transaccion comercial sino tambien un importante intercambio humano. Mi prioridad es casjhvbsdkjva vahjkbfvajdbvkuahdj vkae vjahevbaehj vkyuaerv ajehrvjhe vkaer vhea vaehjrv aehr vehv djhvkahdjv kaehr vhae djhe vhjda vjh jhsdbvjhasdv na dvjkhsbdvjhbsdjhvbas dvjhavjhds vjhasd vhjsv jhbsd vjhxbsjvhsd cjhavkyearv ajherv jweyvkawev kwuyvwayuv aywe vyukwav werh fke fgaer fmhea mhbed ahd fkage dfkgkdjhf kjhdf jhd h kjadhf ahjwe fjhd fjjfhwd fajhfjhaewf ajwe fjahewfjwahe ake gmaehjg amdb daj akjehr gaje fakedfhg ajkejghra kewhgvakgehae gkh gku3y kwuy4 kwhej ghawje gahjerg adb akgjdb jab khv adkjhva kjhfev kjrhv akejvg aekhvga krjhrva</p>
                <%= link_to "Comienza Ahora!", new_user_registration_path, class: "btn btn-default btn-xl" %>
            </div>
        </div>
    </div>
</section>

app/views/pages/home.html.erb
<h1>Bienvenidoa Rita Balboa Propiedades</h1>

app/views/pages/user_properties.html.erb
<section class="bg-primary" id="about">
    <div class="container">

      <p id="notice"><%= notice %></p>

      <h1>Mis Propiedades</h1>

      <table>
        <thead>
          <tr>
            <th>Direccion</th>
            <th>Precio</th>
            <th>Cliente</th>

          </tr>
        </thead>



        <div class="container-fluid">
          <div class="row">
          <% @user_properties.each do |property| %>
              <div class="col-xs-6 col-md-4">
                <div class="thumbnail">
                  <%= image_tag property.image.url(:medium) %>
                  <div class="caption">
                  <% if user_signed_in? %>
                    <h3><%= property.direccion %></h3>
                    <p><%= property.user.email %></p>
                    <p>$ <%= property.precio %></p>
                    <%= link_to 'Show', property, class: "btn btn-success" %>
                    <%= link_to 'Edit', edit_property_path(property) %>
                    <%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %>
                  <% else %>
                    <h3><%= property.direccion %></h3>
                    <p><%= property.user.email %></p>
                    <p>$ <%= property.precio %></p>
                    <%= link_to 'Show', property, class: "btn btn-success" %>
                  <% end %>
        
                  </div>
                </div>
              </div>
          <% end %>
          </div>
        </div>



      </table>
  </div>
</section>

app/views/properties/_form.html.erb
<div class="panel panel-default">

<div class="panel-heading">
<h2 class="panel-title">Ingresa los datos</h2>
</div>


<%= form_for @property, url: properties_path, html: { multipart: true } do |f| %>

  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% @property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="panel-body">
    <div class="form-group">
      <%= f.label :Foto_Principal %>
      <%= f.file_field :image %>
    </div>
    
    <div class="form-group">
        <%= f.label :Direccion %>
        <%= f.text_field :direccion, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= f.label :Comuna %>
        <%= f.text_field :comuna, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= f.label :Ciudad %>
        <%= f.text_field :ciudad, class: "form-control" %>
    </div>

      <div class="form-group">
        <%= f.label :Casa %>
        <%= f.check_box :casa %>
    </div>
   
    <div class="form-group">
        <%= f.label :Departamento %>
        <%= f.check_box :departamento %>
    </div>

    <div class="form-group">
        <%= f.label :Terreno %>
        <%= f.check_box :terreno %>
    </div>

      <div class="form-group">
        <%= f.label :Descripcion %>
        <%= f.text_field :descripcion, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= f.label :Precio %>
        <%= f.text_field :precio, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= f.label :Baños %>
        <%= f.number_field :banos, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= f.label :Superficie_total %>
        <%= f.text_field :superficie_total, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= f.label :Amoblado %>
        <%= f.text_field :amoblado, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= f.label :Estacionamiento %>
        <%= f.number_field :estacionamiento, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= f.label :Bodega %>
        <%= f.check_box :bodega %>
    </div>

    <div class="form-group">
        <%= f.label :Estado %>
        <%= f.text_field :estado, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= f.label :GastosComunes %>
        <%= f.text_field :gastos_comunes, class: "form-control" %>
    </div>


    <div class="form-group">
        <%= f.label :Comentarios %>
        <%= f.text_area :comentarios, class: "form-control" %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>

    <% end %>
  </div>

</div>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form' %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<header>
    <div class="header-content">
        <div class="header-content-inner">
          
        </div>
    </div>
</header>

<section class="bg-primary" id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <h2 class="section-heading">Tenemos lo que necesitas!</h2>
                <hr class="light">
                <p class="text-faded">Start Bootstrap has everything you need to get your new website up and running in no time! All of the templates and themes on Start Bootstrap are open source, free to download, and easy to use. No strings attached!</p>
                <a href="#" class="btn btn-default btn-xl">Get Started!</a>
            </div>
        </div>
    </div>
</section>

<section id="services">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">A Tu Servicio</h2>
                <hr class="primary">
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa-diamond wow bounceIn text-primary"></i>
                    <h3>Sturdy Templates</h3>
                    <p class="text-muted">Our templates are updated regularly so they don't break.</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa-paper-plane wow bounceIn text-primary" data-wow-delay=".1s"></i>
                    <h3>Ready to Ship</h3>
                    <p class="text-muted">You can use this theme as is, or you can make changes!</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa-newspaper-o wow bounceIn text-primary" data-wow-delay=".2s"></i>
                    <h3>Up to Date</h3>
                    <p class="text-muted">We update dependencies to keep things fresh.</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa-heart wow bounceIn text-primary" data-wow-delay=".3s"></i>
                    <h3>Made with Love</h3>
                    <p class="text-muted">You have to make your websites with love these days!</p>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="no-padding" id="portfolio">
    <div class="container-fluid">
        <div class="row no-gutter">
            <% @properties.each do |property| %>
            <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <%= image_tag property.image.url(:medium), class: "img-responsive" %>
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                <%= property.direccion %>
                            </div>
                            <div class="project-name">
                                $ <%= property.precio %>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <% end %>
        </div>
    </div>
</section>

<aside class="bg-dark">
    <div class="container text-center">
        <div class="call-to-action">
            <h2>Administra tus propiedades!</h2>
            <%= link_to "Registrate", new_user_registration_path, class: "btn btn-default btn-xl wow tada" %>
        </div>
    </div>
</aside>

<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <h2 class="section-heading">Contactame!</h2>
                <hr class="primary">
                <p>Listo para publicar tu propiedad? Contactame al celular o enviame un correo electronico.</p>
            </div>
            <div class="col-lg-4 col-lg-offset-2 text-center">
                <i class="fa fa-phone fa-3x wow bounceIn"></i>
                <p>+56 9 84459749</p>
            </div>
            <div class="col-lg-4 text-center">
                <i class="fa fa-envelope-o fa-3x wow bounceIn" data-wow-delay=".1s"></i>
                <p><a href="mailto:ritabalboar@hotmail.com">ritabalboar@hotmail.com</a></p>
            </div>
        </div>
    </div>
</section>

app/views/properties/new.html.erb
<section class="bg-primary" id="about">
    <div class="container">


		<h1>Nueva Propiedad</h1>

		<%= render 'form' %>

		<%= link_to 'Back', properties_path %>

	</div>
</section>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<table>
	<th>Direccion</th>
	<th>Precio</th>
	<th>Cliente</th>
	<tr>
		<td><%= @property.direccion %></td>
		<td><%= @property.precio %></td>
		<td><%= @property.user.email %></td>
		<%= image_tag @property.image.url(:medium), class: "img-rounded" %>
	</tr>
</table>

</br>
<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>

app/views/users/_form.html.erb
<%= form_for @user, url: users_path, html: { multipart: true } do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="panel-body">

   <div class="form-group">
        <%= f.label :nombre %>
        <%= f.text_field :nombre, class: "form-control" %>
    </div>

   <div class="form-group">
        <%= f.label :apellido %>
        <%= f.text_field :apellido, class: "form-control" %>
    </div>

   <div class="form-group">
        <%= f.label :telefono %>
        <%= f.number_field :telefono, class: "form-control" %>
    </div>

   <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: "form-control" %>
    </div>
    

     <div class="actions">
      <%= f.submit %>
    </div>

    
   </div>

<% end %>

app/views/users/index.html.erb
<section class="bg-primary" id="about">
    <div class="container">
    
		<table>
			<tr>Nombre</tr>
			<tr>Apellido</tr>
			<tr>Telefono</tr>
				<% @users.each do |user| %>
				<td>
					<%= user.nombre %>
					<%= user.apellido %>
					<%= user.telefono %>
				</td>
				<% end %>
		</table>

	</div>
</section>

app/views/users/new.html.erb
<section class="bg-primary" id="about">
    <div class="container">


		<h1>Nuevo Cliente</h1>

		<%= render 'form' %>

		<%= link_to 'Back', root_path %>

	</div>
</section>

app/views/users/show.html.erb
<section class="bg-primary" id="about">
    <div class="container">

    <table>
    <% @user.each do |user| %>
    	<th>Nombre</th>
    	<th>Apellido</th>
    	<th>Telefono</th>
    	<th>email</th>
			<tr><%= user.nombre %></tr>
    	</th>
    	<% end %>
    </table>

	</div>
</section>